- package.json
I noticed that the [npm page](https://www.npmjs.com/package/@turbopuffer/turbopuffer) doesn’t have the links like I’m used to seeing (repo and homepage). I looked into it and I think it needs to follow this format in the package.json to be picked up on that page and other websites.
> Add website and repo links to package.json

- .eslintrc.js
- package-lock.json
- package.json
- src/turbopuffer.ts
- tsconfig.json
Adds industry-standard typescript linter (eslint) and formatter (prettier) to project. This should make the library much more robust, maintainable, and type-safe.
I've also added an eslint config for hooking in widely used plugins that substantially extend the linting rules to warn on a greater set of issues. The dev dependencies I've added are:
* [`@typescript-eslint/eslint-plugin`](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin): widely used plugin for linting Typescript
* [`@typescript-eslint/parser`](https://www.npmjs.com/package/@typescript-eslint/parser): widely used companion plugin to the above - allows linting [Typescript AST](https://typescript-eslint.io/packages/parser/)
* `eslint`: base eslint plugin
* …
> Add eslint and prettier

- src/turbopuffer.test.ts
- src/turbopuffer.ts
metrics object looks like
```
{
approx_namespace_size: 2,
cache_hit_ratio: 1,
cache_temperature: 'warm',
processing_time: 108,
exhaustive_search_count: 2
}
```
> add queryWithMetrics function to return response headers

- src/turbopuffer.ts
I don't see any reason not to compress, reduces a 20kB query with a 1536 dimension vector and some filters to 8kB.
> compress query response body

- package-lock.json
- package.json
- src/httpClient.ts
- src/turbopuffer.test.ts
- src/turbopuffer.ts
avoids lumping these two parts of response processing together
> add deserialize_time metric and fix body_read_time

- package-lock.json
- package.json
- src/httpClient.ts
- src/turbopuffer.test.ts
- src/turbopuffer.ts
according to the undici docs this method is much faster than fetch https://github.com/nodejs/undici/tree/main#benchmarks
my preliminary performance testing agrees with this, notably better combined body_read_time+deserialize_time when the process is under load
this is passing tests and should work, but could use:
- advantages of streamed gunzip:
- in theory it's better to pipeline the cpu work with the io
- advantages of oneshot gunzip:
- can time the body read and gunzip separately
- maybe drive i/o faster to buffer the whole response sooner
- fewer context switches to C
> use undici.request for httpClient

- package-lock.json
- package.json
- src/httpClient.ts
- src/turbopuffer.test.ts
- src/turbopuffer.ts
In cases with very fast, underutilized networks, CPU may be a more sparse. In those cases, it can be advisable to disable compression.
@pushrax
> http: allow disabling compression

- package-lock.json
- package.json
- src/turbopuffer.ts
Currently, if the main module (turbopuffer.ts) does not export a type, end-users cannot import them directly from @turbopuffer/turbopuffer; instead they'll have to import from @turbopuffer/turbopuffer/dist/types which is not very DX-friendly:
```ts
import { Turbopuffer } from "@turbopuffer/turbopuffer"
import { Vector } from "@turbopuffer/turbopuffer/dist/types"
```
Re-exporting all types in types.ts in the main module makes this nicer:
```ts
import { Turbopuffer, Vector } from "@turbopuffer/turbopuffer"
```
> Fix type exports: Re-export types in main module

- package-lock.json
- package.json
- src/turbopuffer.ts
Currently, you have to do:
```ts
await tpuf.namespaces({});
```
If we're not passing any of the obj arg fields, just doing the following should work (I think this is nicer and also matches the python client):
```ts
await tpuf.namespaces();
```
> Make .namespaces() obj arg optional

- README.md
- package-lock.json
- package.json
- src/httpClient/default.ts
- src/httpClient/node.ts
- src/turbopuffer.test.ts
If `baseUrl` already ends in a `/`, the end URL can become something like `https://gcp-europe-west3.turbopuffer.com//v1/namespaces/my_amazing_namespace/schema` and cause issues.
Additionally, when query params need to be added, the ? separator can be duplicated and cause issues. Eg. with a `.export({ cursor: 'my_next_cursor' })` call, the path would become `/v1/namespaces/export_testing??cursor=my_next_cursor` and thus not fetch the next page of results.
From https://developer.mozilla.org/en-US/docs/Web/API/URL/search:
> The search property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface is a search string, also called a query string, that is a string containing a "?" followed by the parameters of the URL. If the URL does not have a search query, this property …
> Fix url path building

- src/turbopuffer.test.ts
- src/types.d.ts
To help users avoid typos in their schema definitions (e.g., `boolean` instead of `bool`, or `integer` instead of `uint`).
> Enumerate acceptable values on schema `type` field

- package-lock.json
- package.json
- src/turbopuffer.test.ts
- src/turbopuffer.ts
adds a `ns.updateSchema()` method (https://turbopuffer.com/docs/schema), similar to the Python SDK's `update_schema()`
> add ns.updateSchema()

- src/turbopuffer.test.ts
- src/types.ts
[string] is an array with exactly one string element, rather than an array with any number of string elements, as was intended.
> Fix type of RankBy_Text

- README.md
- package-lock.json
- package.json
- src/helpers.ts
- src/turbopuffer.test.ts
- src/turbopuffer.ts
- src/types.ts
One test expected to fail until https://github.com/turbopuffer/turbopuffer/pull/3697 goes in.
----
This is a SemVer-breaking change, as it introduces the following non-backwards compatible changes:
* The `QueryResults` type changes from a list of rows directly to a type containing `rows: QueryRow[]`.
* The `queryWithMetrics` method is removed in favor of returning performance metrics with every query via the new `QueryResults.performance` field.
* `rank_by` is now a required parameter to `query`.
* The `vector` parameter to query is removed and replaced by `rank_by: ["vector", "ANN", ...]`.
* The `include_vectors` parameter to query is removed and replaced by `include_attributes: ["vector", ...]`.
* Specifying `include_attributes: true` now includes the `vector` attribute.
* The …
> Use v2 query API

- README.md
- src/turbopuffer.test.ts
- src/turbopuffer.ts
To align with a forthcoming change to the backend API. The goal is to limit a longstanding confusion where users issue a query and don't realize there's a default top_k of 10. (Most databases default to an unlimited result set size.)
> [TPUF-358] Mandate `top_k` in `query`

- package-lock.json
- package.json
- src/helpers.ts
- src/httpClient/default.ts
- src/httpClient/node.ts
- src/turbopuffer.test.ts
for better DX, allow users to use a baseUrl without the protocol (this is what browsers implicitly do too for eg.). One scenario where this can happen is if you copy a region from the site regions page
> handle case when baseUrl doesnt have protocol

- src/resources/namespaces.ts
- tests/api-resources/namespaces.test.ts
This type was missing the necessary custom code to stitch in our stricter types for the `aggregate_by`, `filters`, and `rank_by` parameters.
> fix: strict types for async query and multi_query APIs

- src/client.ts
- tests/custom.test.ts
- tests/index.test.ts
This has tripped up a few BYOC customers.
> fix: don't require region unless baseUrl contains {region} placeholder

- scripts/build
- scripts/utils/fix-bundle-ignore-imports.cjs
- scripts/utils/smoke-test.cjs
- scripts/utils/smoke-test.mjs
- src/internal/shims.ts
- src/lib/compressor.ts
Beef up the smoke test in scripts/build that checks the validity of the compiles JavaScript so that it can detect the issue @Arash-11 is fixing in #117.
> build: improve smoke test

- src/resources/namespaces.ts
- tests/api-resources/namespaces.test.ts
Unfortunately Stainless can't handle this automatically during codegen.
> fix: use strict types for explainQuery
